Day 3 & Day 4/blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles do
    member do
      post 'report'
    end
    resources :comments
  end
  root 'articles#index'
end

Day 3 & Day 4/blog/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    can :read, Article

    can :manage, Article, user_id: user.id

    if user.admin?
      can :manage, Article
    end
  end
end

Day 3 & Day 4/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Day 3 & Day 4/blog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_one_attached :image
    has_many :reports, class_name: 'Report'

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  
    enum status: { draft: 0, published: 1, archived: 2 }
    attribute :article_status, :integer, default: 0
    scope :active, -> { where(archived: false) }

    # Callback to archive article if reports count is 3
    before_save :archive_article, if: -> { reports_count >= 3 }
    def reports_count
        # Logic to calculate reports count goes here
        # For example, you might query related models to count reports
        reports.count
      end
  
    private
  
    def archive_article
        self.archived = true
    end
  end
  

Day 3 & Day 4/blog/app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

Day 3 & Day 4/blog/app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end
  
    class_methods do
      def public_count
        where(status: 'public').count
      end
    end
  
    def archived?
      status == 'archived'
    end
  end
  

Day 3 & Day 4/blog/app/models/report.rb
class Report < ApplicationRecord
    belongs_to :article
    belongs_to :user

end

Day 3 & Day 4/blog/app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  has_many :reports


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Day 3 & Day 4/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Day 3 & Day 4/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
    @articles = current_user.articles.where(archived: false)
    @Articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = current_user.articles.find(params[:id])
  end

  def update
    @article = current_user.articles.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = current_user.articles.find(params[:id])
    if @article.destroy
      puts "Article successfully destroyed."
    end

    redirect_to root_path, notice: 'Article was successfully destroyed.'
  end

  def report
    @article = Article.find(params[:id])
    @article.increment!(:reports_count)
    if @article.reports_count >= 3
      @article.update(archived: true)
      flash[:alert] = 'Article has been archived due to multiple reports.'
    else
      flash[:notice] = 'Article has been reported.'
    end
    redirect_to @article
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status, :image)
  end
end

Day 3 & Day 4/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
      end

      def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
      end
    
      private
        def comment_params
          params.require(:comment).permit(:commenter, :body , :status)
        end
end

Day 3 & Day 4/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

Day 3 & Day 4/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

Day 3 & Day 4/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

Day 3 & Day 4/blog/app/views/articles/_form.html.erb
<%= form_with model: article, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Article.statuses.keys.map { |status| [status.humanize, status] }, selected: article.status || 'public' %>
  </div>

  <div>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Day 3 & Day 4/blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

Day 3 & Day 4/blog/app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @Articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
      <% if current_user == article.user %>
        <%= link_to "Edit", edit_article_path(article) %>
        <%= link_to "destroy", article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

Day 3 & Day 4/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

Day 3 & Day 4/blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<%= image_tag @article.image if @article.image.attached? %>

<% if current_user == @article.user %>
  <%= link_to "Edit", edit_article_path(@article) %>
  <li>
    <%= link_to "Destroy", article_path(@article), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </li>
  <%= link_to "Report", report_article_path(@article), data: {
    turbo_method: :post,
    turbo_confirm: "Are you sure you want to report this article?"
  } %>
<% end %>

<h2>Comments</h2>
<%= render @article.comments %>
<%= render 'comments/form', article: @article %>

Day 3 & Day 4/blog/app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
  </p>
<% end %>

Day 3 & Day 4/blog/app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <p>
  <%= form.label :status %><br>
  <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

Day 3 & Day 4/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>